name: cst2335_final_project
description: "This project is for the CST2335 Graphical Interface Programming course at Algonquin College. It's an airline management app with modules for managing customers, airplanes, flights, and reservations. Each team member handles a specific module, ensuring modular design and effective collaboration via GitHub."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  floor: ^1.2.0
  floor_annotation: ^1.0.0
  sqflite: ^2.0.0+4
  intl: ^0.17.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  build_runner: ^2.1.2
  floor_generator: ^1.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
